// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.ButtonDispenser;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController wheel_ActuatorWheelActuatorMotor;
    public static SpeedController brush_ActuatorBrushActuatorMotor;
    public static Relay lEDSpike1;
    public static Relay lEDSpike2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        wheel_ActuatorWheelActuatorMotor = new Jaguar(1, 1);
	LiveWindow.addActuator("Wheel_Actuator", "WheelActuatorMotor", (Jaguar) wheel_ActuatorWheelActuatorMotor);
        
        brush_ActuatorBrushActuatorMotor = new Jaguar(1, 2);
	LiveWindow.addActuator("Brush_Actuator", "BrushActuatorMotor", (Jaguar) brush_ActuatorBrushActuatorMotor);
        
        lEDSpike1 = new Relay(1, 1);
	LiveWindow.addActuator("LED", "Spike 1", lEDSpike1);
        
        lEDSpike2 = new Relay(1, 2);
	LiveWindow.addActuator("LED", "Spike 2", lEDSpike2);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
