// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.ButtonDispenser.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc3244.ButtonDispenser.Robot;

/**
 *
 */
public class  dispense_CommandGroup extends CommandGroup {

    public dispense_CommandGroup() {
        addSequential(new Dispense_Button_Timed(1, 0.1));
        addParallel(new Flash_LED(5));
        waitForChildren();
    }
}
