// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.ButtonDispenser.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3244.ButtonDispenser.Robot;

/**
 *
 */
public class  Flash_LED extends Command {

    private int m_cycles = 0;
    private int m_cycleCounter = 0;
    private Timer t = new Timer();
    public Flash_LED(int cycles) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lED);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        m_cycles = cycles;
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.lED.off();
        m_cycleCounter = 0;
        t.reset();
        t.start();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        if(t.get()>.5){
            Robot.LED.on();
        }else if(t.get()>1){
            Robot.LED.off();
            m_cycleCounter = m_cycleCounter + 1;
            t.reset();
        }
       
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return m_cycles > m_cycleCounter;
    }

    // Called once after isFinished returns true
    protected void end() {
        Robot.lED.off();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
